apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf  # Target file
          subPath: nginx.conf  # Specify the single file inside ConfigMap
  volumes:
    - name: nginx-config-volume
      configMap:
        name: nginx-config
