apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-live
spec:
  containers:
    - name: nginx-container-live
      image: nginx
      ports:
        - containerPort: 80
      startupProbe:
        exec:
          command: ["curl","http://localhost:80"]
        initialDelaySeconds: 0  
        periodSeconds: 5         
        failureThreshold: 3      